# Generated by Django 3.2.8 on 2022-08-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatos',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
